name: "GraphJSON.org"
description: "A JSON specificaiton format for Graphs - Graphs for everyone!"
baseurl: "http://graphalchemist.github.io/GraphJSON"

kramdown:
  input: GFM
  auto_ids: false

pygments: true